@echo off

set ip="%~dp0AndroidStudioPortable\data\idea.properties"
set APMD=$_32_

mkdir "%~dp0AndroidStudioPortable_TEMP\"
"%~dp0bin\7-Zip\7z.exe" x "%~1" -o"%~dp0AndroidStudioPortable_TEMP\"

IF NOT EXIST "%~dp0AndroidStudioPortable_TEMP\%APMD%\" (
    set APMD=$_31_
)

del "%~dp0AndroidStudioPortable_TEMP\%APMD%\uninstall.exe"
mkdir "%~dp0AndroidStudioPortable"
xcopy "%~dp0bin\android-studio-portable\" "%~dp0AndroidStudioPortable\" /e /y
xcopy "%~dp0AndroidStudioPortable_TEMP\%APMD%\" "%~dp0AndroidStudioPortable\app\" /e /y
rmdir "%~dp0AndroidStudioPortable_TEMP\" /s /q

rem setx ANDROID_HOME "E:\ASP\ASP_Subscriptions\AndroidStudioPortable\data\sdk" /M

echo ^<application^> > "%~dp0AndroidStudioPortable\data\config\options\android.sdk.path.xml"
echo   ^<component name="AndroidSdkPathStore"^> >> "%~dp0AndroidStudioPortable\data\config\options\android.sdk.path.xml"
echo     ^<option name="androidSdkAbsolutePath" value="%~dp0AndroidStudioPortable\data\sdk" /^> >> "%~dp0AndroidStudioPortable\data\config\options\android.sdk.path.xml"
echo   ^</component^> >> "%~dp0AndroidStudioPortable\data\config\options\android.sdk.path.xml"
echo ^</application^> >> "%~dp0AndroidStudioPortable\data\config\options\android.sdk.path.xml"

echo # DO NOT EDIT! AUTOMATICALLY GENERATED BY PORTAPPS. > %ip%

setlocal enabledelayedexpansion

set "path_icp=idea.config.path=%~dp0AndroidStudioPortable\data\config"
set "path_icp=!path_icp:\=/!"
echo !path_icp! >> %ip%

set "path_isp=idea.system.path=%~dp0AndroidStudioPortable\data\system"
set "path_isp=!path_isp:\=/!"
echo !path_isp! >> %ip%

set "path_ipp=idea.plugins.path=%~dp0AndroidStudioPortable\data\plugins"
set "path_ipp=!path_ipp:\=/!"
echo !path_ipp! >> %ip%

set "path_ilp=idea.log.path=%~dp0AndroidStudioPortable\data\log"
set "path_ilp=!path_ilp:\=/!"
echo !path_ilp! >> %ip%

set "path_isp=idea.sdk.path=%~dp0AndroidStudioPortable\data\sdk"
set "path_isp=!path_isp:\=/!"
echo !path_isp! >> %ip%

endlocal

cls
echo.
echo Unpack complete!
echo.
pause